export const CATEGORY_MAP: Record<string, string> = {
  water: "everyday Essentials",

  // Produce
  onion: "Produce",
  redOnion: "Produce",
  greenOnion: "Produce",
  tomato: "Produce",
  cherryTomato: "Produce",
  potato: "Produce",
  sweetPotato: "Produce",
  garlic: "Produce",
  ginger: "Produce",
  carrot: "Produce",
  celery: "Produce",
  bellpepper: "Produce",
  jalapeno: "Produce",
  chili: "Produce",
  spinach: "Produce",
  kale: "Produce",
  lettuce: "Produce",
  cabbage: "Produce",
  zucchini: "Produce",
  eggplant: "Produce",
  broccoli: "Produce",
  cauliflower: "Produce",
  mushroom: "Produce",
  asparagus: "Produce",
  corn: "Produce",
  peas: "Produce",
  avocado: "Produce",
  apple: "Produce",
  banana: "Produce",
  orange: "Produce",
  lemon: "Produce",
  lime: "Produce",
  strawberry: "Produce",
  blueberry: "Produce",
  grape: "Produce",
  pineapple: "Produce",

  // Dairy
  milk: "Dairy",
  almondMilk: "Dairy",
  oatMilk: "Dairy",
  butter: "Dairy",
  cheese: "Dairy",
  cheddar: "Dairy",
  mozzarella: "Dairy",
  parmesan: "Dairy",
  yogurt: "Dairy",
  greekYogurt: "Dairy",
  cream: "Dairy",
  sourCream: "Dairy",
  ghee: "Dairy",
  paneer: "Dairy",
  eggs: "Dairy",

  // Pantry / Grains / Staples
  oil: "Pantry",
  oliveOil: "Pantry",
  vegetableOil: "Pantry",
  coconutOil: "Pantry",
  rice: "Pantry",
  brownRice: "Pantry",
  basmatiRice: "Pantry",
  jasmineRice: "Pantry",
  flour: "Pantry",
  allPurposeFlour: "Pantry",
  wholeWheatFlour: "Pantry",
  cornmeal: "Pantry",
  sugar: "Pantry",
  brownSugar: "Pantry",
  powderedSugar: "Pantry",
  honey: "Pantry",
  mapleSyrup: "Pantry",
  vinegar: "Pantry",
  appleCiderVinegar: "Pantry",
  soySauce: "Pantry",
  tamari: "Pantry",
  fishSauce: "Pantry",
  pasta: "Pantry",
  spaghetti: "Pantry",
  penne: "Pantry",
  noodles: "Pantry",
  ramen: "Pantry",
  quinoa: "Pantry",
  couscous: "Pantry",
  oats: "Pantry",
  breadcrumbs: "Pantry",
  bakingPowder: "Pantry",
  bakingSoda: "Pantry",
  yeast: "Pantry",
  cornstarch: "Pantry",

  // Beans / Legumes
  lentils: "Pantry",
  redLentils: "Pantry",
  greenLentils: "Pantry",
  chickpeas: "Pantry",
  blackBeans: "Pantry",
  kidneyBeans: "Pantry",
  pintoBeans: "Pantry",
  navyBeans: "Pantry",

  // Spices & Herbs
  salt: "Spices",
  seaSalt: "Spices",
  pepper: "Spices",
  blackPepper: "Spices",
  whitePepper: "Spices",
  turmeric: "Spices",
  cumin: "Spices",
  coriander: "Spices",
  paprika: "Spices",
  smokedPaprika: "Spices",
  chiliPowder: "Spices",
  cayenne: "Spices",
  garamMasala: "Spices",
  cinnamon: "Spices",
  nutmeg: "Spices",
  cloves: "Spices",
  cardamom: "Spices",
  bayLeaf: "Spices",
  oregano: "Spices",
  thyme: "Spices",
  rosemary: "Spices",
  basil: "Spices",
  parsley: "Spices",

  // Sauces & Condiments
  ketchup: "Pantry",
  mustard: "Pantry",
  mayonnaise: "Pantry",
  bbqSauce: "Pantry",
  hotSauce: "Pantry",
  sriracha: "Pantry",
  hoisinSauce: "Pantry",
  teriyakiSauce: "Pantry",

  // Meat
  chicken: "Meat",
  chickenBreast: "Meat",
  chickenThigh: "Meat",
  beef: "Meat",
  groundBeef: "Meat",
  steak: "Meat",
  pork: "Meat",
  bacon: "Meat",
  sausage: "Meat",
  lamb: "Meat",

  // Seafood
  fish: "Seafood",
  salmon: "Seafood",
  tuna: "Seafood",
  cod: "Seafood",
  tilapia: "Seafood",
  shrimp: "Seafood",
  prawns: "Seafood",
  crab: "Seafood",

  // Bakery
  bread: "Bakery",
  bagels: "Bakery",
  buns: "Bakery",
  tortillas: "Bakery",
  naan: "Bakery",
  pita: "Bakery",

  // Frozen
  frozenVegetables: "Frozen",
  frozenFruit: "Frozen",
  frozenFries: "Frozen",
  frozenPizza: "Frozen",
  iceCream: "Frozen",

  // Snacks & Misc
  chips: "Snacks",
  crackers: "Snacks",
  popcorn: "Snacks",
  nuts: "Snacks",
  almonds: "Snacks",
  peanuts: "Snacks",
  cashews: "Snacks",
};
